import type { Dict } from "./dict";

export const en: Dict = {
  code: "en",
  htmlLang: "en",
  name: "English",
  meta: {
    title: "DogFlow — a training plan built around your dog",
    description:
      "Take the 2-minute quiz and get a training plan matched to your dog's breed, age and behaviour problems.",
  },
  common: {
    continue: "Continue",
    back: "Back",
    skip: "Skip this question",
    none: "None of the above",
    selectAll: "Select all that apply",
    of: "of",
    yourDog: "your dog",
  },
  sections: {
    dog: "About your dog",
    behaviour: "Behaviour",
    training: "Training routine",
  },
  landing: {
    variants: [
      { id: "leash", pre: "Walk with no leash pulling", highlight: "in 1 day" },
      { id: "potty", pre: "Potty trained in the right spot", highlight: "in 3 days" },
      { id: "biting", pre: "Stop the play biting", highlight: "in 3 hours" },
      { id: "behaviour", pre: "Cut the unwanted behaviour", highlight: "in 2 days" },
      { id: "alone", pre: "Your puppy home alone, drama free,", highlight: "in 5 hours" },
    ],
    consent:
      "By tapping Continue you confirm that you have read and accept the Privacy Policy and Terms of Use, and agree to the processing of your personal data.",
    privacy: "Privacy Policy",
    terms: "Terms of Use",
    cta: "Continue",
  },
  steps: {
    dog_sex: { question: "Your dog is", options: { female: "Female", male: "Male" } },
    dog_name: {
      question: "What's your dog's name?",
      placeholder: "Your dog's name",
      skip: "I'd rather not say",
    },
    dog_age: {
      question: "How old is {dog}?",
      options: {
        m0_6: "0 to 6 months",
        m7_12: "7 to 12 months",
        y1_2: "1 to 2 years",
        y2_7: "2 to 7 years",
        y7plus: "Over 7 years",
      },
    },
    dog_breed: { question: "What breed is {dog}?" },
    proof_breed: {
      headline: "Over 150,000 {breed} dogs have trained with us",
      body: "{dog}'s plan will use exactly what worked for them.",
      headlineGeneric: "Over 150,000 owners just like you have trained with us",
      bodyGeneric: "{dog}'s plan will use exactly what worked for them.",
    },
    dog_health: {
      question: "Does {dog} have any health issues in these areas?",
      hint: "Select all that apply",
      options: {
        healthy: "My dog is healthy",
        vision: "Vision",
        hearing: "Hearing",
        joints: "Joints",
      },
    },
    potty: {
      question: "How is {dog} doing with potty training?",
      hint: "Select all that apply",
      options: {
        no_routine: "No consistent routine yet",
        night: "Can't hold it through the night",
        alone: "Accidents when left home alone",
      },
    },
    home_issues: {
      question: "What problems do you have with {dog} at home?",
      hint: "Select all that apply",
      options: {
        crate: "Struggles with crate training",
        biting: "Biting",
        barking: "Barking",
        chewing: "Chews or destroys furniture",
      },
    },
    walk_issues: {
      question: "And on walks, what happens?",
      hint: "Select all that apply",
      options: {
        not_outside: "{dog} doesn't go outside yet",
        pulling: "Pulls on the leash",
        eats_trash: "Eats things off the ground",
      },
    },
    activity: {
      question: "What's {dog}'s energy level during the day?",
      options: {
        very: "Very active, never settles",
        moderate: "Moderate, rests after burning energy",
        low: "Low, mostly lying down and sleeping",
      },
    },
    heard_you: {
      headline: "We hear you",
      body: "Every answer reshapes {dog}'s plan. Just a few more questions and the routine is ready.",
    },
    commands_known: {
      question: "Check everything {dog} already does without hesitating",
      hint: "Select all that apply",
      options: {
        name: "Responds to their name",
        heel: "Heel",
        no: "No",
        food_lure: "Follows a treat",
        touch: "Touch",
        look: "Look at me",
        stand: "Stand",
        place: "Place",
        down: "Down",
        drop: "Drop it",
      },
    },
    scale_ignores: {
      question: "How much do you relate to this?",
      body: "“{dog} often ignores my commands and won't obey.”",
      minLabel: "Not at all",
      maxLabel: "Completely",
    },
    scale_bond: {
      question: "And to this one?",
      body: "“I want a strong bond with {dog} and to enjoy the time we spend together.”",
      minLabel: "Not at all",
      maxLabel: "Completely",
    },
    reason: {
      question: "Any particular reason to train {dog} right now?",
      hint: "Select all that apply",
      options: {
        new_dog: "I adopted a new dog",
        baby: "A baby is on the way",
        moving: "I'm moving house",
        wedding: "Wedding or someone moving in",
        work_schedule: "Change in my work schedule",
        travel: "Travel plans",
        guests: "Hosting guests",
        just_wellbehaved: "No, I just want a well-behaved dog",
      },
    },
    moving_date: {
      question: "Exciting! When is the move?",
      hint: "This lets us fit the training in before the date.",
      options: { already: "It already happened" },
      skip: "Skip this question",
    },
    trained_before: {
      question: "Have you trained {dog} before?",
      options: {
        pro: "Yes, with a professional trainer",
        alone: "Yes, on my own",
        not_yet: "Not yet, but I plan to",
      },
    },
    owner_age: {
      question: "What's your age range?",
      hint: "This helps us set {dog}'s plan at a pace that fits you.",
      options: {
        a18_24: "18 to 24",
        a25_34: "25 to 34",
        a35_44: "35 to 44",
        a45_54: "45 to 54",
        a55plus: "55 or older",
      },
    },
    time_together: {
      question: "Do you enjoy the time you spend with {dog}?",
      options: {
        love: "Love it, best part of my day",
        sometimes: "Sometimes, when we're both up for it",
        not_enough: "Not as much as I'd like",
        challenge: "Honestly, it's been a challenge",
      },
    },
  },
  breeds: {
    search: "Search breed",
    common: "Most common breeds",
    unknown: "I don't know my dog's breed",
    list: [
      "Mixed breed",
      "Golden Retriever",
      "Labrador Retriever",
      "Pit Bull",
      "Shih Tzu",
      "Poodle",
      "Yorkshire Terrier",
      "French Bulldog",
      "German Shepherd",
      "Border Collie",
      "Beagle",
      "Rottweiler",
      "Dachshund",
      "Chihuahua",
      "Miniature Pinscher",
      "Siberian Husky",
      "Lhasa Apso",
      "Maltese",
      "Pomeranian",
      "Boxer",
      "Cocker Spaniel",
      "Schnauzer",
      "Akita",
      "Pug",
      "Basset Hound",
      "Doberman",
      "Saint Bernard",
      "Dalmatian",
    ],
  },
  prediction: {
    eyebrow: "Our forecast for your dog",
    headlinePre: "{dog} will master",
    headlineHighlight: "8+ commands by {date}",
    headlinePost: "and leave the unwanted behaviour behind.",
    now: "Today",
    nowItems: ["Behaviours to fix", "1 command"],
    goal: "Goal",
    goalItems: ["Well-behaved dog", "8+ commands"],
  },
  building: {
    headline: "Building {dog}'s training plan...",
    tasks: [
      "Identifying the behaviours to fix",
      "Assessing the commands {dog} already knows",
      "Adapting the lessons for a {breed}",
      "Building your personalised plan",
    ],
    testimonial: {
      handle: "@caroline.pet",
      title: "It actually works!",
      body: "I finished the obedience module with my dog last week and the difference on walks is unreal.",
    },
  },
  planReady: {
    headline: "{dog}'s training plan is ready",
    profile: "Training profile",
    cta: "See my plan",
    labels: { name: "Name", breed: "Breed", age: "Age" },
  },
  email: {
    headline: "{dog}'s personalised plan is ready!",
    subhead: "Enter your e-mail to get the plan and track the progress.",
    label: "E-mail",
    placeholder: "you@example.com",
    cta: "Get my plan",
    privacy:
      "We handle your data under our Privacy Policy and never share it with third parties.",
    invalid: "Please enter a valid e-mail.",
  },
  optin: {
    headline: "Want training tips and special offers by e-mail?",
    yes: "Yes, send them",
    no: "Not interested",
  },
  discount: {
    headline: "Save on your personalised plan",
    subhead: "A welcome discount for {dog}'s training plan",
    cta: "Get my discount",
    off: "off",
    scratchHint: "Scratch the card with your finger",
    wonHeadline: "You got 60% off",
    wonSubhead: "The top prize is yours!",
    wonCta: "Continue",
  },
  offer: {
    timer: "Your personal offer expires in",
    promoTitle: "Coupon applied!",
    promoBadge: "60% off",
    planNames: {
      p7: "7-day plan",
      p4: "4-week plan",
      p12: "12-week plan",
    },
    popular: "Most popular",
    perDay: "per day",
    weekly: "per week",
    total: "total",
    billed: "You pay {amount} today",
    cta: "Get my plan",
    stat: "98% of our users notice positive changes in their dog's behaviour within the first week of training.",
    whyHeadline: "Why DogFlow works",
    why: [
      "A plan built around your dog's breed, age and problems",
      "15 minutes a day is enough to see progress",
      "Over 70 short, easy-to-follow lessons",
      "Over 80 games and tricks to burn energy and build the bond",
      "Guidance on grooming, health and feeding",
      "Train at home or outdoors, no equipment needed",
    ],
    guaranteeEyebrow: "Guarantee",
    guaranteeTitle: "30-day money-back guarantee",
    guaranteeBody:
      "We believe you'll see results in 4 weeks. Follow the plan and if you don't see a concrete change, we refund you. Details and limits in the Terms of Use.",
    faqHeadline: "Frequently asked questions",
    faq: [
      {
        q: "How long until I see the first results?",
        a: "Most dogs show some progress in the very first session. Within a few weeks the difference is usually obvious to the whole household.",
      },
      {
        q: "Does DogFlow work as well as a trainer?",
        a: "The lessons follow the same positive-reinforcement methods a good trainer uses, with the advantage that you train at your own pace and repeat as often as you like.",
      },
      {
        q: "Are the training results permanent?",
        a: "Yes, as long as the commands stay part of the routine. The plan includes short maintenance drills for exactly that reason.",
      },
      {
        q: "Is it for adult dogs or only puppies?",
        a: "Both. The plan changes based on the age you gave in the quiz, and there are separate tracks for puppies and adult dogs.",
      },
    ],
    testimonialsHeadline: "Stories from people who trained with us",
    testimonials: [
      {
        handle: "@caroline.pet",
        title: "It actually works!",
        body: "I finished the obedience module with my dog last week and the difference on walks is unreal.",
      },
      {
        handle: "@rafa_3861",
        title: "Problem gone",
        body: "Really happy with the app. The accidents indoors simply stopped.",
      },
      {
        handle: "@thor.family",
        title: "My dog stopped pulling",
        body: "Within three days Thor was walking beside me with a loose leash. I never expected it to be that fast.",
      },
    ],
    contact: "Still have a question? Write to",
    expired: "Your offer has expired.",
    restart: "Reopen my offer",
  },
  login: {
    headline: "Sign in to DogFlow",
    subhead: "Enter the e-mail you used at checkout. We'll send an access link — no password.",
    label: "E-mail",
    placeholder: "you@example.com",
    cta: "Send access link",
    sending: "Sending...",
    sentHeadline: "Link sent",
    sentBody: "Open your e-mail and tap the link to sign in. It's valid for one hour.",
    invalid: "Please enter a valid e-mail.",
    noAccessHeadline: "We couldn't find your purchase",
    noAccessBody: "This e-mail has no active plan. If you bought with a different e-mail, sign in with that one. If you think this is a mistake, get in touch.",
    noAccessCta: "See the plans",
    signedInAs: "Signed in as",
    signOut: "Sign out",
    failed: "We couldn't send the link. Please try again in a moment.",
  },
  success: {
    headline: "You're all set!",
    body: "We've e-mailed you the next steps. In the meantime, take a look at what's inside DogFlow.",
    cta: "Explore the app",
    placeholderNote:
      "Checkout is not connected yet. Set the Hotmart or Kiwify URL in the environment variables to take real payments.",
    paidHeadline: "Payment confirmed!",
    paidBody: "Your dog's plan is active. One step left to get in.",
    paidSteps: [
      "Tap the button below",
      "Enter the same e-mail you used at checkout",
      "Open the link we send and start with the first lesson",
    ],
    paidCta: "Sign in to DogFlow",
    paidHint:
      "Use the same e-mail as the purchase. That is how we recognise your access.",
  },
  member: {
    tabs: { course: "My course", training: "Training", clicker: "Whistle" },
    coursesHeadline: "Courses",
    inProgress: "In progress",
    courses: [
      {
        title: "Puppy — basic course",
        subtitle: "Socialising and the first steps at home",
        lessons: [
          {
            title: "Getting your puppy to stop biting during play",
            body: "You're playing, everything is going well, and suddenly the biting starts on your hands — not always gently. If that sounds familiar, this lesson shows you what to do.",
          },
          { title: "Potty training in the right spot" },
          { title: "Switching focus from one toy to another" },
          { title: "The take-and-drop game" },
          { title: "The “wait” command" },
          { title: "Attention signal" },
          { title: "Teaching your puppy their name" },
          { title: "Getting your puppy used to the crate" },
          { title: "Treat luring: how to use it without creating dependence" },
          { title: "Nose touch to the hand" },
          { title: "Introducing your puppy to new surfaces" },
          { title: "Getting your puppy to love the leash" },
          { title: "Staying calm in front of a toy" },
          { title: "The “look at me” game" },
          { title: "The “find it” command" },
          { title: "Stopping your puppy begging at the table" },
          { title: "How to praise your dog properly" },
        ],
      },
      {
        title: "Adult dog — basic course",
        subtitle: "For dogs over 10 months",
        lessons: [
          { title: "Restarting training with an adult dog" },
          { title: "Loose-leash walking" },
          { title: "A reliable recall in open spaces" },
          { title: "Controlling doorbell barking" },
          { title: "Staying home alone without anxiety" },
        ],
      },
      {
        title: "Boredom-busting games",
        subtitle: "Keep your dog's mind busy",
        lessons: [
          { title: "Game 1 — unroll the towel" },
          { title: "Game 2 — time to open the box" },
          { title: "Game 3 — find the treat among the toys" },
          { title: "Game 4 — the treat hidden in the book" },
          { title: "Game 5 — untie the knot" },
          { title: "Game 6 — the pastry chef game" },
          { title: "Game 7 — the rolling game" },
          { title: "Game 8 — snuffle mat" },
          { title: "Game 9 — the box game" },
        ],
      },
      {
        title: "Tricks that impress",
        subtitle: "Fun tricks that film well",
        lessons: [
          { title: "Shake paw" },
          { title: "Shy" },
          { title: "Paws up" },
          { title: "Figure eight" },
          { title: "Weave through the legs" },
          { title: "Spin around" },
          { title: "Close the door" },
        ],
      },
    ],
    lessonLabel: "Lesson",
    stepLabel: "Step",
    backToCourse: "Back",
    previewNote:
      "Preview of the member area. Videos go into the reserved slots below.",
    stepPlaceholder:
      "The step-by-step for this lesson goes here, alongside the video below.",
    allLessons: "All lessons",
    clickerTitle: "Training clicker",
    clickerBody:
      "Tap to sound the clicker. Use it right after your dog does what you asked — the sound marks the exact moment they got it right.",
    clickerButton: "Tap to click",
    clickerHint: "Works with your device's sound turned on.",
  },
  videoPlaceholder: {
    label: "Reserved video slot",
    hint: "Replace with a 5 to 10 second video",
  },
  imagePlaceholder: "Reserved image slot",
};
