import type { Dict } from "./dict";

export const es: Dict = {
  code: "es",
  htmlLang: "es",
  name: "Español",
  meta: {
    title: "DogFlow — plan de entrenamiento personalizado para tu perro",
    description:
      "Responde un test de 2 minutos y recibe un plan de entrenamiento hecho para la raza, la edad y los problemas de tu perro.",
  },
  common: {
    continue: "Continuar",
    back: "Volver",
    skip: "Saltar esta pregunta",
    none: "Ninguna de las anteriores",
    selectAll: "Marca todo lo que corresponda",
    of: "de",
    yourDog: "tu perro",
  },
  sections: {
    dog: "Sobre tu perro",
    behaviour: "Comportamiento",
    training: "Rutina de entrenamiento",
  },
  landing: {
    variants: [
      { id: "leash", pre: "Pasea sin tirones de correa", highlight: "en 1 día" },
      { id: "potty", pre: "Que haga sus necesidades en el sitio correcto", highlight: "en 3 días" },
      { id: "biting", pre: "Se acabaron los mordiscos en el juego", highlight: "en 3 horas" },
      { id: "behaviour", pre: "Corta el comportamiento no deseado", highlight: "en 2 días" },
      { id: "alone", pre: "Tu cachorro solo en casa, sin dramas,", highlight: "en 5 horas" },
    ],
    consent:
      "Al pulsar Continuar declaras que leíste y aceptas la Política de Privacidad y los Términos de Uso, y que estás de acuerdo con el tratamiento de tus datos personales.",
    privacy: "Política de Privacidad",
    terms: "Términos de Uso",
    cta: "Continuar",
  },
  steps: {
    dog_sex: { question: "Tu perro es", options: { female: "Hembra", male: "Macho" } },
    dog_name: {
      question: "¿Cómo se llama tu perro?",
      placeholder: "Nombre de tu perro",
      skip: "Prefiero no decirlo",
    },
    dog_age: {
      question: "¿Cuántos años tiene {dog}?",
      options: {
        m0_6: "0 a 6 meses",
        m7_12: "7 a 12 meses",
        y1_2: "1 a 2 años",
        y2_7: "2 a 7 años",
        y7plus: "Más de 7 años",
      },
    },
    dog_breed: { question: "¿Cuál es la raza de {dog}?" },
    proof_breed: {
      headline: "Más de 150 mil perros de raza {breed} ya entrenaron con nosotros",
      body: "El plan de {dog} va a usar exactamente lo que funcionó con ellos.",
    },
    dog_health: {
      question: "¿{dog} tiene algún problema de salud en estas áreas?",
      hint: "Marca todo lo que corresponda",
      options: {
        healthy: "Mi perro está sano",
        vision: "Visión",
        hearing: "Audición",
        joints: "Articulaciones",
      },
    },
    potty: {
      question: "¿Cómo va {dog} con sus necesidades?",
      hint: "Marca todo lo que corresponda",
      options: {
        no_routine: "Todavía no tiene una rutina fija",
        night: "No aguanta toda la noche",
        alone: "Tiene accidentes cuando se queda solo en casa",
      },
    },
    home_issues: {
      question: "¿Qué problemas tienes con {dog} dentro de casa?",
      hint: "Marca todo lo que corresponda",
      options: {
        crate: "Dificultad con el transportín",
        biting: "Mordiscos",
        barking: "Ladridos",
        chewing: "Muerde o destroza los muebles",
      },
    },
    walk_issues: {
      question: "Y en el paseo, ¿qué pasa?",
      hint: "Marca todo lo que corresponda",
      options: {
        not_outside: "{dog} todavía no sale a la calle",
        pulling: "Tira de la correa",
        eats_trash: "Come basura del suelo",
      },
    },
    activity: {
      question: "¿Cuál es el nivel de energía de {dog} durante el día?",
      options: {
        very: "Muy inquieto, no para nunca",
        moderate: "Moderado, descansa después de gastar energía",
        low: "Bajo, se pasa el día tumbado",
      },
    },
    heard_you: {
      headline: "Entendemos tu caso",
      body: "Cada respuesta cambia el plan de {dog}. Faltan pocas preguntas para armar la rutina correcta.",
    },
    commands_known: {
      question: "Marca todo lo que {dog} ya hace sin dudar",
      hint: "Marca todo lo que corresponda",
      options: {
        name: "Responde a su nombre",
        heel: "Junto",
        no: "No",
        food_lure: "Sigue el premio",
        touch: "Toca",
        look: "Mírame",
        stand: "De pie",
        place: "A tu sitio",
        down: "Tumbado",
        drop: "Suelta",
      },
    },
    scale_ignores: {
      question: "¿Cuánto te identificas con esta frase?",
      body: "«{dog} ignora mis órdenes a menudo y no obedece».",
      minLabel: "Para nada",
      maxLabel: "Totalmente",
    },
    scale_bond: {
      question: "¿Y con esta?",
      body: "«Quiero crear un vínculo fuerte con {dog} y disfrutar del tiempo que pasamos juntos».",
      minLabel: "Para nada",
      maxLabel: "Totalmente",
    },
    reason: {
      question: "¿Hay algún motivo concreto para entrenar a {dog} ahora?",
      hint: "Marca todo lo que corresponda",
      options: {
        new_dog: "Adopté un perro nuevo",
        baby: "Viene un bebé en camino",
        moving: "Voy a mudarme",
        wedding: "Boda o nuevo conviviente",
        work_schedule: "Cambio de horario en el trabajo",
        travel: "Planes de viaje",
        guests: "Voy a recibir visitas",
        just_wellbehaved: "No, solo quiero un perro bien educado",
      },
    },
    moving_date: {
      question: "¡Qué bien! ¿Cuándo es la mudanza?",
      hint: "Así encajamos el entrenamiento antes de esa fecha.",
      options: { already: "Ya ocurrió" },
      skip: "Saltar esta pregunta",
    },
    trained_before: {
      question: "¿Ya entrenaste a {dog} antes?",
      options: {
        pro: "Sí, con un adiestrador profesional",
        alone: "Sí, por mi cuenta",
        not_yet: "Todavía no, pero pienso hacerlo",
      },
    },
    owner_age: {
      question: "¿En qué rango de edad estás?",
      hint: "Esto ayuda a ajustar el plan de {dog} a tu ritmo.",
      options: {
        a18_24: "18 a 24 años",
        a25_34: "25 a 34 años",
        a35_44: "35 a 44 años",
        a45_54: "45 a 54 años",
        a55plus: "55 años o más",
      },
    },
    time_together: {
      question: "¿Disfrutas del tiempo que pasas con {dog}?",
      options: {
        love: "Me encanta, es lo mejor de mi día",
        sometimes: "A veces, cuando los dos tenemos ganas",
        not_enough: "No tanto como me gustaría",
        challenge: "Sinceramente, está siendo un desafío",
      },
    },
  },
  breeds: {
    search: "Buscar raza",
    common: "Razas más comunes",
    unknown: "No sé la raza de mi perro",
    list: [
      "Mestizo",
      "Golden Retriever",
      "Labrador Retriever",
      "Pit Bull",
      "Shih Tzu",
      "Caniche",
      "Yorkshire",
      "Bulldog Francés",
      "Pastor Alemán",
      "Border Collie",
      "Beagle",
      "Rottweiler",
      "Teckel (Salchicha)",
      "Chihuahua",
      "Pinscher",
      "Husky Siberiano",
      "Lhasa Apso",
      "Bichón Maltés",
      "Pomerania",
      "Bóxer",
      "Cocker Spaniel",
      "Schnauzer",
      "Akita",
      "Carlino (Pug)",
      "Basset Hound",
      "Doberman",
      "San Bernardo",
      "Dálmata",
    ],
  },
  prediction: {
    eyebrow: "Nuestra previsión para tu perro",
    headlinePre: "{dog} va a dominar",
    headlineHighlight: "más de 8 órdenes para el {date}",
    headlinePost: "y dejar atrás los comportamientos no deseados.",
    now: "Hoy",
    nowItems: ["Comportamientos a corregir", "1 orden"],
    goal: "Objetivo",
    goalItems: ["Perro bien educado", "8+ órdenes"],
  },
  building: {
    headline: "Armando el plan de entrenamiento de {dog}...",
    tasks: [
      "Identificando los comportamientos a corregir",
      "Evaluando las órdenes que {dog} ya domina",
      "Adaptando las clases a un {breed}",
      "Construyendo tu plan personalizado",
    ],
    testimonial: {
      handle: "@carolina.pet",
      title: "¡Funciona de verdad!",
      body: "Terminé el módulo de obediencia con mi perra la semana pasada y la diferencia en el paseo es brutal.",
    },
  },
  planReady: {
    headline: "El plan de entrenamiento de {dog} está listo",
    profile: "Perfil de entrenamiento",
    cta: "Ver mi plan",
    labels: { name: "Nombre", breed: "Raza", age: "Edad" },
  },
  email: {
    headline: "¡El plan personalizado de {dog} está listo!",
    subhead: "Escribe tu correo para recibir el plan y seguir el progreso.",
    label: "Correo electrónico",
    placeholder: "tucorreo@ejemplo.com",
    cta: "Recibir mi plan",
    privacy:
      "Cuidamos tus datos según nuestra Política de Privacidad y no los compartimos con terceros.",
    invalid: "Escribe un correo válido.",
  },
  optin: {
    headline: "¿Quieres recibir consejos de entrenamiento y ofertas por correo?",
    yes: "¡Sí, envíamelos!",
    no: "No me interesa",
  },
  discount: {
    headline: "Ahorra en tu plan personalizado",
    subhead: "Elige un descuento de bienvenida para el plan de {dog}",
    cta: "Quiero mi descuento",
    off: "off",
    wonHeadline: "Ganaste un 60% de descuento",
    wonSubhead: "¡El premio mayor es tuyo!",
    wonCta: "Continuar",
  },
  offer: {
    timer: "Tu oferta personal expira en",
    promoTitle: "¡Cupón aplicado!",
    promoBadge: "60% de descuento",
    planNames: {
      p7: "Plan de 7 días",
      p4: "Plan de 4 semanas",
      p12: "Plan de 12 semanas",
    },
    popular: "Más popular",
    perDay: "por día",
    weekly: "por semana",
    total: "en total",
    billed: "Hoy pagas {amount}",
    cta: "Quiero mi plan",
    stat: "El 98% de nuestros usuarios nota cambios positivos en el comportamiento de su perro ya en la primera semana.",
    whyHeadline: "Por qué funciona DogFlow",
    why: [
      "Plan personalizado según la raza, la edad y los problemas de tu perro",
      "Con 15 minutos al día ya se ve evolución",
      "Más de 70 clases cortas y fáciles de seguir",
      "Más de 80 juegos y trucos para gastar energía y crear vínculo",
      "Pautas de higiene, salud y alimentación",
      "Entrena en casa o en la calle, sin equipo especial",
    ],
    guaranteeEyebrow: "Garantía",
    guaranteeTitle: "30 días de garantía de reembolso",
    guaranteeBody:
      "Creemos que verás resultados en 4 semanas. Si sigues el plan y no notas un cambio concreto, te devolvemos el dinero. Detalles y límites en los Términos de Uso.",
    faqHeadline: "Preguntas frecuentes",
    faq: [
      {
        q: "¿En cuánto tiempo se ven los primeros resultados?",
        a: "La mayoría de los perros muestra alguna mejora ya en la primera sesión. En pocas semanas la diferencia suele ser evidente para toda la familia.",
      },
      {
        q: "¿DogFlow funciona tan bien como un adiestrador?",
        a: "Las clases siguen los mismos métodos de refuerzo positivo que usa un buen adiestrador, con la ventaja de que entrenas a tu ritmo y repites cuantas veces quieras.",
      },
      {
        q: "¿El resultado del entrenamiento es permanente?",
        a: "Sí, siempre que las órdenes entren en la rutina. El plan incluye ejercicios cortos de mantenimiento justo para que no se pierda el aprendizaje.",
      },
      {
        q: "¿Sirve para perro adulto o solo para cachorro?",
        a: "Sirve para ambos. El plan cambia según la edad que indicaste en el test, y tenemos rutas separadas para cachorro y perro adulto.",
      },
    ],
    testimonialsHeadline: "Historias de quienes ya entrenaron",
    testimonials: [
      {
        handle: "@carolina.pet",
        title: "¡Funciona de verdad!",
        body: "Terminé el módulo de obediencia con mi perra la semana pasada y la diferencia en el paseo es brutal.",
      },
      {
        handle: "@rafa_3861",
        title: "Se acabó el problema",
        body: "Estoy muy contento con la app. Los accidentes dentro de casa simplemente pararon.",
      },
      {
        handle: "@familia.thor",
        title: "Mi perro dejó de tirar",
        body: "En tres días Thor ya caminaba a mi lado sin tensar la correa. Nunca imaginé que fuera tan rápido.",
      },
    ],
    contact: "¿Tienes dudas? Escríbenos a",
    expired: "Tu oferta expiró.",
    restart: "Reabrir mi oferta",
  },
  login: {
    headline: "Entrar en DogFlow",
    subhead: "Escribe el correo que usaste en la compra. Te enviamos un enlace de acceso, sin contraseña.",
    label: "Correo electrónico",
    placeholder: "tucorreo@ejemplo.com",
    cta: "Enviar enlace de acceso",
    sending: "Enviando...",
    sentHeadline: "Enlace enviado",
    sentBody: "Abre tu correo y toca el enlace para entrar. Vale por una hora.",
    invalid: "Escribe un correo válido.",
    noAccessHeadline: "No encontramos tu compra",
    noAccessBody: "Este correo no tiene un plan activo. Si compraste con otro correo, entra con ese. Si crees que es un error, escríbenos.",
    noAccessCta: "Ver los planes",
    signedInAs: "Conectado como",
    signOut: "Salir",
    failed: "No pudimos enviar el enlace. Inténtalo de nuevo en un momento.",
  },
  success: {
    headline: "¡Todo listo!",
    body: "Te enviamos los siguientes pasos por correo. Mientras tanto, echa un vistazo a lo que hay dentro de DogFlow.",
    cta: "Explorar la app",
    placeholderNote:
      "El checkout aún no está conectado. Configura la URL de Hotmart o Kiwify en las variables de entorno para cobrar de verdad.",
  },
  member: {
    tabs: { course: "Mi curso", training: "Entrenamiento", clicker: "Silbato" },
    coursesHeadline: "Cursos",
    inProgress: "En curso",
    courses: [
      {
        title: "Cachorro — curso básico",
        subtitle: "Socialización y los primeros pasos en casa",
        lessons: [
          {
            title: "Hacer que el cachorro deje de morder durante el juego",
            body: "Estáis jugando, todo va bien, y de repente llegan los mordiscos en las manos — no siempre suaves. Si te suena familiar, esta clase te muestra qué hacer.",
          },
          { title: "Entrenamiento de necesidades en el sitio correcto" },
          { title: "Cambiando el foco de un juguete a otro" },
          { title: "El juego de «coge y suelta»" },
          { title: "La orden «espera»" },
          { title: "Señal de atención" },
          { title: "Enseñando su nombre al cachorro" },
          { title: "Acostumbrando al cachorro al transportín" },
          { title: "Guiar con premio: cómo usarlo sin crear dependencia" },
          { title: "Tocar la mano con el hocico" },
          { title: "Presentando nuevas superficies al cachorro" },
          { title: "Haciendo que el cachorro quiera su correa" },
          { title: "Mantener la calma delante del juguete" },
          { title: "Juego «mírame»" },
          { title: "La orden «busca»" },
          { title: "Evitar que el cachorro pida comida en la mesa" },
          { title: "Cómo felicitar a tu perro correctamente" },
        ],
      },
      {
        title: "Perro adulto — curso básico",
        subtitle: "Para perros de más de 10 meses",
        lessons: [
          { title: "Retomando el entrenamiento con un perro adulto" },
          { title: "Paseo sin tirones de correa" },
          { title: "Llamada fiable en espacio abierto" },
          { title: "Controlando los ladridos en el timbre" },
          { title: "Quedarse solo en casa sin ansiedad" },
        ],
      },
      {
        title: "Juegos contra el aburrimiento",
        subtitle: "Mantén la cabeza de tu perro ocupada",
        lessons: [
          { title: "Juego 1 — desenrollar la toalla" },
          { title: "Juego 2 — hora de abrir la caja" },
          { title: "Juego 3 — encontrar el premio entre los juguetes" },
          { title: "Juego 4 — el premio escondido en el libro" },
          { title: "Juego 5 — deshacer el nudo" },
          { title: "Juego 6 — el juego del pastelero" },
          { title: "Juego 7 — juego de rodar" },
          { title: "Juego 8 — alfombra olfativa" },
          { title: "Juego 9 — el juego de la caja" },
        ],
      },
      {
        title: "Trucos para impresionar",
        subtitle: "Trucos divertidos que quedan bien en vídeo",
        lessons: [
          { title: "Dar la pata" },
          { title: "Vergüenza" },
          { title: "Patas arriba" },
          { title: "Figura en ocho" },
          { title: "Entrelazar las piernas" },
          { title: "Dar la vuelta" },
          { title: "Cerrar la puerta" },
        ],
      },
    ],
    lessonLabel: "Clase",
    stepLabel: "Paso",
    backToCourse: "Volver",
    previewNote:
      "Vista previa del área de miembros. Los vídeos van en los espacios reservados de abajo.",
    stepPlaceholder:
      "El paso a paso de esta clase va aquí, junto con el vídeo de abajo.",
  },
  videoPlaceholder: {
    label: "Espacio reservado para el vídeo",
    hint: "Sustituye por un vídeo de 5 a 10 segundos",
  },
  imagePlaceholder: "Espacio reservado para la imagen",
};
