import type { Dict } from "./dict";

export const pt: Dict = {
  code: "pt",
  htmlLang: "pt-BR",
  name: "Português",
  meta: {
    title: "DogFlow — plano de treino personalizado para o seu cão",
    description:
      "Responda a um teste de 2 minutos e receba um plano de treino feito para a raça, a idade e os problemas do seu cão.",
  },
  common: {
    continue: "Continuar",
    back: "Voltar",
    skip: "Pular esta pergunta",
    none: "Nenhuma das opções",
    selectAll: "Marque tudo o que se aplica",
    of: "de",
    yourDog: "o seu cão",
  },
  sections: {
    dog: "Sobre o seu cão",
    behaviour: "Comportamento",
    training: "Rotina de treino",
  },
  landing: {
    variants: [
      { id: "leash", pre: "Passeie sem puxões de trela", highlight: "em 1 dia" },
      { id: "potty", pre: "Xixi e cocô no lugar certo", highlight: "em 3 dias" },
      { id: "biting", pre: "Fim das mordidas na brincadeira", highlight: "em 3 horas" },
      { id: "behaviour", pre: "Corte o comportamento indesejado", highlight: "em 2 dias" },
      { id: "alone", pre: "Seu filhote sozinho em casa, sem drama,", highlight: "em 5 horas" },
    ],
    consent:
      "Ao tocar em Continuar, você declara que leu e aceita a Política de Privacidade e os Termos de Uso, e concorda com o tratamento dos seus dados pessoais.",
    privacy: "Política de Privacidade",
    terms: "Termos de Uso",
    cta: "Continuar",
  },
  steps: {
    dog_sex: {
      question: "O seu cão é",
      options: { female: "Fêmea", male: "Macho" },
    },
    dog_name: {
      question: "Como o seu cão se chama?",
      placeholder: "Nome do seu cão",
      skip: "Prefiro não dizer",
    },
    dog_age: {
      question: "Quantos anos {dog} tem?",
      options: {
        m0_6: "0 a 6 meses",
        m7_12: "7 a 12 meses",
        y1_2: "1 a 2 anos",
        y2_7: "2 a 7 anos",
        y7plus: "Mais de 7 anos",
      },
    },
    dog_breed: { question: "Qual é a raça de {dog}?" },
    proof_breed: {
      headline: "Mais de 150 mil cães da raça {breed} já treinaram com a gente",
      body: "O plano de {dog} vai usar exatamente o que funcionou com eles.",
      headlineGeneric: "Mais de 150 mil tutores como você já treinaram com a gente",
      bodyGeneric: "O plano de {dog} vai usar exatamente o que funcionou com eles.",
    },
    dog_health: {
      question: "{dog} tem alguma questão de saúde nestas áreas?",
      hint: "Marque tudo o que se aplica",
      options: {
        healthy: "Meu cão é saudável",
        vision: "Visão",
        hearing: "Audição",
        joints: "Articulações",
      },
    },
    potty: {
      question: "Como está o treino de xixi e cocô de {dog}?",
      hint: "Marque tudo o que se aplica",
      options: {
        no_routine: "Ainda não tem uma rotina fixa",
        night: "Não consegue segurar a noite inteira",
        alone: "Faz escapadas quando fica sozinho em casa",
      },
    },
    home_issues: {
      question: "Que problemas você enfrenta com {dog} dentro de casa?",
      hint: "Marque tudo o que se aplica",
      options: {
        crate: "Dificuldade com a caixa de transporte",
        biting: "Mordidas",
        barking: "Latidos",
        chewing: "Rói ou destrói os móveis",
      },
    },
    walk_issues: {
      question: "E na hora do passeio, o que acontece?",
      hint: "Marque tudo o que se aplica",
      options: {
        not_outside: "{dog} ainda não sai na rua",
        pulling: "Puxa a trela",
        eats_trash: "Come lixo do chão",
      },
    },
    activity: {
      question: "Qual é o nível de energia de {dog} durante o dia?",
      options: {
        very: "Muito agitado, não para quieto",
        moderate: "Moderado, descansa depois de gastar energia",
        low: "Baixo, vive deitado e dormindo",
      },
    },
    heard_you: {
      headline: "Entendemos o seu caso",
      body: "Cada resposta sua muda o plano de {dog}. Faltam poucas perguntas para montarmos a rotina certa.",
    },
    commands_known: {
      question: "Marque tudo o que {dog} já faz sem hesitar",
      hint: "Marque tudo o que se aplica",
      options: {
        name: "Atende pelo nome",
        heel: "Junto",
        no: "Não",
        food_lure: "Segue o petisco",
        touch: "Toca",
        look: "Olha para mim",
        stand: "Em pé",
        place: "Lugar",
        down: "Deita",
        drop: "Larga",
      },
    },
    scale_ignores: {
      question: "O quanto você se identifica com esta frase?",
      body: "“{dog} ignora as minhas ordens com frequência e não obedece.”",
      minLabel: "Nem um pouco",
      maxLabel: "Totalmente",
    },
    scale_bond: {
      question: "E com esta?",
      body: "“Quero criar um vínculo forte com {dog} e curtir o tempo que passamos juntos.”",
      minLabel: "Nem um pouco",
      maxLabel: "Totalmente",
    },
    reason: {
      question: "Tem algum motivo específico para treinar {dog} agora?",
      hint: "Marque tudo o que se aplica",
      options: {
        new_dog: "Adotei um cão novo",
        baby: "Vem bebê chegando",
        moving: "Vou mudar de casa",
        wedding: "Casamento ou novo morador",
        work_schedule: "Mudança no horário de trabalho",
        travel: "Planos de viagem",
        guests: "Vou receber visitas",
        just_wellbehaved: "Não, só quero um cão bem-educado",
      },
    },
    moving_date: {
      question: "Que legal! Quando é a mudança?",
      hint: "Assim conseguimos encaixar o treino antes da data.",
      options: { already: "Já aconteceu" },
      skip: "Pular esta pergunta",
    },
    trained_before: {
      question: "Você já treinou {dog} antes?",
      options: {
        pro: "Sim, com um adestrador profissional",
        alone: "Sim, por conta própria",
        not_yet: "Ainda não, mas pretendo",
      },
    },
    owner_age: {
      question: "Qual é a sua faixa de idade?",
      hint: "Isso ajuda a deixar o plano de {dog} no ritmo certo para você.",
      options: {
        a18_24: "18 a 24 anos",
        a25_34: "25 a 34 anos",
        a35_44: "35 a 44 anos",
        a45_54: "45 a 54 anos",
        a55plus: "55 anos ou mais",
      },
    },
    time_together: {
      question: "Você gosta de passar tempo com {dog}?",
      options: {
        love: "Amo, é o melhor da minha rotina",
        sometimes: "Às vezes, quando nós dois estamos a fim",
        not_enough: "Não tanto quanto eu gostaria",
        challenge: "Sinceramente, tem sido um desafio",
      },
    },
  },
  breeds: {
    search: "Buscar raça",
    common: "Raças mais comuns",
    unknown: "Não sei a raça do meu cão",
    list: [
      "Vira-lata (SRD)",
      "Golden Retriever",
      "Labrador Retriever",
      "Pit Bull",
      "Shih Tzu",
      "Poodle",
      "Yorkshire",
      "Bulldog Francês",
      "Pastor Alemão",
      "Border Collie",
      "Beagle",
      "Rottweiler",
      "Dachshund (Salsicha)",
      "Chihuahua",
      "Pinscher",
      "Husky Siberiano",
      "Lhasa Apso",
      "Maltês",
      "Spitz Alemão (Lulu)",
      "Boxer",
      "Cocker Spaniel",
      "Schnauzer",
      "Akita",
      "Pug",
      "Basset Hound",
      "Doberman",
      "São Bernardo",
      "Dálmata",
    ],
  },
  prediction: {
    eyebrow: "Nossa previsão para o seu cão",
    headlinePre: "{dog} vai dominar",
    headlineHighlight: "mais de 8 comandos até {date}",
    headlinePost: "e deixar para trás os comportamentos indesejados.",
    now: "Hoje",
    nowItems: ["Comportamentos a corrigir", "1 comando"],
    goal: "Objetivo",
    goalItems: ["Cão bem-educado", "8+ comandos"],
  },
  building: {
    headline: "Montando o plano de treino de {dog}...",
    tasks: [
      "Identificando os comportamentos a corrigir",
      "Avaliando os comandos que {dog} já domina",
      "Adaptando as aulas para um {breed}",
      "Montando o seu plano personalizado",
    ],
    testimonial: {
      handle: "@carolzinha.pet",
      title: "Funcionou mesmo!",
      body: "Terminei o módulo de obediência com a minha cadela semana passada e a diferença no passeio é absurda.",
    },
  },
  planReady: {
    headline: "O plano de treino de {dog} está pronto",
    profile: "Perfil de treino",
    cta: "Ver o meu plano",
    labels: { name: "Nome", breed: "Raça", age: "Idade" },
  },
  email: {
    headline: "O plano personalizado de {dog} está pronto!",
    subhead: "Digite seu e-mail para receber o plano e acompanhar o progresso.",
    label: "E-mail",
    placeholder: "seuemail@exemplo.com",
    cta: "Receber o meu plano",
    privacy:
      "Cuidamos dos seus dados conforme a nossa Política de Privacidade e não compartilhamos informações com terceiros.",
    invalid: "Digite um e-mail válido.",
  },
  optin: {
    headline: "Quer receber dicas de treino e ofertas especiais por e-mail?",
    yes: "Pode mandar!",
    no: "Não tenho interesse",
  },
  discount: {
    headline: "Economize no seu plano personalizado",
    subhead: "Um desconto de boas-vindas para o plano de treino de {dog}",
    cta: "Pegar o meu desconto",
    off: "off",
    scratchHint: "Raspe o cartão com o dedo",
    wonHeadline: "Você ganhou 60% de desconto",
    wonSubhead: "O prêmio principal é seu!",
    wonCta: "Continuar",
  },
  offer: {
    timer: "Sua oferta pessoal expira em",
    promoTitle: "Cupom aplicado!",
    promoBadge: "60% de desconto",
    planNames: {
      p7: "Plano de 7 dias",
      p4: "Plano de 4 semanas",
      p12: "Plano de 12 semanas",
    },
    popular: "Mais popular",
    perDay: "por dia",
    weekly: "por semana",
    total: "no total",
    billed: "Você paga {amount} hoje",
    cta: "Quero o meu plano",
    stat: "98% dos nossos usuários percebem mudanças positivas no comportamento do cão já na primeira semana de treino.",
    whyHeadline: "Por que o DogFlow funciona",
    why: [
      "Plano personalizado para a raça, a idade e os problemas do seu cão",
      "15 minutos por dia bastam para ver evolução",
      "Mais de 70 aulas curtas e fáceis de seguir",
      "Mais de 80 jogos e truques para gastar energia e criar vínculo",
      "Orientações de higiene, saúde e alimentação",
      "Treine em casa ou na rua, sem precisar de equipamento",
    ],
    guaranteeEyebrow: "Garantia",
    guaranteeTitle: "30 dias de garantia de reembolso",
    guaranteeBody:
      "Acreditamos que você vai ver resultado em 4 semanas. Se seguir o plano e não perceber mudança concreta, devolvemos o seu dinheiro. Detalhes e limites nos Termos de Uso.",
    faqHeadline: "Perguntas frequentes",
    faq: [
      {
        q: "Em quanto tempo aparecem os primeiros resultados?",
        a: "A maioria dos cães mostra alguma evolução já na primeira sessão. Em poucas semanas a diferença costuma ser bem visível para a família inteira.",
      },
      {
        q: "O DogFlow funciona tão bem quanto um adestrador?",
        a: "As aulas seguem os mesmos métodos de reforço positivo que um bom adestrador usa, com a vantagem de você treinar no seu ritmo e repetir quantas vezes quiser.",
      },
      {
        q: "O resultado do treino é permanente?",
        a: "Sim, desde que os comandos entrem na rotina. O plano inclui exercícios curtos de manutenção justamente para o aprendizado não se perder.",
      },
      {
        q: "Serve para cão adulto ou só para filhote?",
        a: "Serve para os dois. O plano muda conforme a idade que você informou no teste, e temos trilhas separadas para filhote e cão adulto.",
      },
    ],
    testimonialsHeadline: "Histórias de quem já treinou",
    testimonials: [
      {
        handle: "@carolzinha.pet",
        title: "Funcionou mesmo!",
        body: "Terminei o módulo de obediência com a minha cadela semana passada e a diferença no passeio é absurda.",
      },
      {
        handle: "@rafa_3861",
        title: "Acabou o problema",
        body: "Estou muito feliz com o app. Os escapes de xixi dentro de casa simplesmente pararam.",
      },
      {
        handle: "@familia.thor",
        title: "Meu cão parou de puxar",
        body: "Em três dias o Thor já andava do meu lado sem esticar a guia. Nunca imaginei que fosse tão rápido.",
      },
    ],
    contact: "Ficou com dúvida? Escreva para",
    expired: "Sua oferta expirou.",
    restart: "Reabrir a minha oferta",
  },
  login: {
    headline: "Entrar no DogFlow",
    subhead: "Digite o e-mail que você usou na compra. Enviamos um link de acesso — sem senha.",
    label: "E-mail",
    placeholder: "seuemail@exemplo.com",
    cta: "Enviar link de acesso",
    sending: "Enviando...",
    sentHeadline: "Link enviado",
    sentBody: "Abra o seu e-mail e toque no link para entrar. Ele vale por uma hora.",
    invalid: "Digite um e-mail válido.",
    noAccessHeadline: "Não encontramos a sua compra",
    noAccessBody: "Este e-mail não tem um plano ativo. Se você comprou com outro e-mail, entre com ele. Se acha que é um engano, fale com a gente.",
    noAccessCta: "Ver os planos",
    signedInAs: "Conectado como",
    signOut: "Sair",
    failed: "Não conseguimos enviar o link. Tente de novo em instantes.",
  },
  success: {
    headline: "Tudo certo!",
    body: "Enviamos os próximos passos para o seu e-mail. Enquanto isso, dá uma olhada no que tem dentro do DogFlow.",
    cta: "Explorar o app",
    placeholderNote:
      "Checkout ainda não conectado. Configure a URL da Hotmart ou Kiwify nas variáveis de ambiente para cobrar de verdade.",
    paidHeadline: "Pagamento confirmado!",
    paidBody:
      "O plano do seu cão já está liberado. Falta só um passo para entrar.",
    paidSteps: [
      "Toque no botão abaixo",
      "Digite o mesmo e-mail que você usou na compra",
      "Abra o link que enviamos e comece pela primeira aula",
    ],
    paidCta: "Entrar no DogFlow",
    paidHint:
      "Use o mesmo e-mail da compra. É por ele que reconhecemos o seu acesso.",
  },
  member: {
    tabs: { course: "Meu curso", training: "Treino", clicker: "Apito" },
    coursesHeadline: "Cursos",
    inProgress: "Em andamento",
    courses: [
      {
        title: "Filhote — curso básico",
        subtitle: "Socialização e os primeiros passos dentro de casa",
        lessons: [
          {
            title: "Fazendo o filhote parar de morder durante a brincadeira",
            body: "Vocês estão brincando, tudo indo bem, e de repente vêm as mordidas nas suas mãos — nem sempre delicadas. Se isso soa familiar, esta aula mostra o que fazer.",
          },
          { title: "Treino de xixi e cocô no lugar certo" },
          { title: "Trocando o foco de um brinquedo para outro" },
          { title: "O jogo do “pega e solta”" },
          { title: "O comando “espera”" },
          { title: "Sinal de atenção" },
          { title: "Ensinando o nome ao seu filhote" },
          { title: "Acostumando o filhote à caixa de transporte" },
          { title: "Condução por petisco: como usar sem viciar" },
          { title: "Encostando o focinho na mão" },
          { title: "Apresentando novas superfícies ao filhote" },
          { title: "Fazendo o filhote gostar da guia" },
          { title: "Mantendo a calma diante do brinquedo" },
          { title: "Jogo “olha para mim”" },
          { title: "O comando “procura”" },
          { title: "Fazendo o filhote parar de pedir comida na mesa" },
          { title: "Como elogiar o seu cão do jeito certo" },
        ],
      },
      {
        title: "Cão adulto — curso básico",
        subtitle: "Para cães com mais de 10 meses",
        lessons: [
          { title: "Recomeçando o treino com um cão adulto" },
          { title: "Passeio sem puxar a guia" },
          { title: "Chamada confiável em ambiente aberto" },
          { title: "Controlando os latidos na campainha" },
          { title: "Ficando sozinho em casa sem ansiedade" },
        ],
      },
      {
        title: "Jogos contra o tédio",
        subtitle: "Mantenha a cabeça do seu cão ocupada",
        lessons: [
          { title: "Jogo 1 — desenrolar a toalha" },
          { title: "Jogo 2 — hora de abrir a caixa" },
          { title: "Jogo 3 — achar o petisco entre os brinquedos" },
          { title: "Jogo 4 — o petisco escondido no livro" },
          { title: "Jogo 5 — desatar o nó" },
          { title: "Jogo 6 — o jogo do confeiteiro" },
          { title: "Jogo 7 — jogo de rolar" },
          { title: "Jogo 8 — tapete de cheiro" },
          { title: "Jogo 9 — jogo da caixa" },
        ],
      },
      {
        title: "Truques para impressionar",
        subtitle: "Truques divertidos que rendem vídeo bom",
        lessons: [
          { title: "Dá a pata" },
          { title: "Vergonha" },
          { title: "Patas para cima" },
          { title: "Figura em oito" },
          { title: "Entrelaçar as pernas" },
          { title: "Dá a volta" },
          { title: "Fecha a porta" },
        ],
      },
    ],
    lessonLabel: "Aula",
    stepLabel: "Passo",
    backToCourse: "Voltar",
    previewNote:
      "Prévia da área de membros. Os vídeos entram nos espaços reservados abaixo.",
    stepPlaceholder:
      "O passo a passo desta aula entra aqui, junto com o vídeo abaixo.",
  },
  videoPlaceholder: {
    label: "Espaço reservado para o vídeo",
    hint: "Substitua por um vídeo de 5 a 10 segundos",
  },
  imagePlaceholder: "Espaço reservado para a imagem",
};
